/**
 * reopt-data.config.mjs — links this repository to its reopt-data analytics project.
 *
 * Read by the `reopt-data` CLI (@reopt-ai/data-cli) and its MCP server. Every command
 * takes `--project-id`, `--organization-id`, `--file`, `--dir` … from here when the
 * flag is not given, so the repository, not the caller, says which project it belongs to.
 *
 * What goes here: ids and paths only.
 *   projectId        the project this code emits events for
 *   organizationId   the organization that owns it (project list, host-app source maps)
 *   apiUrl           deployment origin, only for self-hosted deployments
 *   events.file      the event catalogue (reopt-data.events.json) — `reopt-data event …`
 *   events.types     where `reopt-data event types` writes the .d.ts
 *   sourcemaps.*     defaults for `reopt-data sourcemap upload`
 *
 * What must NOT go here: keys or secrets. This file is committed. Credentials come from
 * REOPT_DATA_ORG_KEY / REOPT_DATA_PLATFORM_KEY / REOPT_DATA_CLIENT_ID + _SECRET in the
 * environment; the CLI refuses a config with unknown keys.
 *
 * Change it with `reopt-data link --…` (merges) or by editing; check with
 * `reopt-data config show`. Precedence: explicit flag > environment > this file.
 * Generated by `reopt-data link`.
 */
import { defineConfig } from "@reopt-ai/data-cli";

export default defineConfig({
  projectId: "cmta2v4g60005zfyqq9eya1he",
  organizationId: "cmta2v4er0001zfyq7565xjco",
  events: {
    file: "./reopt-data.events.json",
    types: "./lib/reopt-events.d.ts",
  },
  sourcemaps: {
    dir: ".next/static",
    urlPrefix: "http://localhost:4100/_next/static",
  },
});
