// Generated by `reopt-data event types` from reopt-data.events.json — do not edit.
// Project cmta2v4g60005zfyqq9eya1he. Re-run after changing the catalogue.

/** Every event the catalogue declares. */
export type ReoptEventName = "$pageview" | "cart.added" | "checkout.submitted" | "order.completed" | "search.performed";

/** Events that are not archived — the ones new code should emit. */
export type ReoptActiveEventName = "$pageview" | "cart.added" | "checkout.submitted" | "order.completed" | "search.performed";

/** Known property keys per event (the rollup properties). Values are untyped until the catalogue carries a property schema. */
export interface ReoptEventProperties {
  "$pageview": { [key: string]: unknown };
  "cart.added": { sku?: unknown; [key: string]: unknown };
  "checkout.submitted": { [key: string]: unknown };
  "order.completed": { currency?: unknown; [key: string]: unknown };
  "search.performed": { query_length?: unknown; [key: string]: unknown };
}
