import type { ReoptActiveEventName } from "@/lib/reopt-events";

/**
 * The events this shop is allowed to emit.
 *
 * `lib/reopt-events.d.ts` is generated by `pnpm events:types` from
 * `reopt-data.events.json`, which is the catalogue committed beside the code
 * that emits it. Generating those types and then importing them nowhere left
 * the catalogue as documentation: the app could emit a name the catalogue had
 * never heard of, and nothing said so until someone read a dashboard. It had
 * already happened — two replay-lab events were live, and asserted on by a
 * spec, without an entry.
 *
 * So every literal event name in this app is written
 * `"name" satisfies ShopEventName`. It costs nothing at runtime and makes
 * `pnpm typecheck` the thing that notices, in the same commit that adds the
 * emission. Adding an event means adding it to the catalogue first.
 */
export type ShopEventName = ReoptActiveEventName;
